#' Return character "dictionary" for converting British to American spellings
#' 
#' Return character "dictionary" for converting British to American spellings.
#' @export


british_to_american_spellings <- function() {
    british_to_american <- character()
    
    # programme instead of program
    british_to_american["programme"] <- "program"
    british_to_american["programm"] <- "program"
    
    # -our instead of -or
    british_to_american["labour"] <- "labor"
    british_to_american["colour"] <- "color"
    british_to_american["honour"] <- "honor"
    british_to_american["flavour"] <- "flavor"
    british_to_american["harbour"] <- "harbor"
    british_to_american["neighbour"] <- "neighbor"
    british_to_american["humour"] <- "humor"
    british_to_american["vigour"] <- "vigor"
    british_to_american["odour"] <- "odor"
    british_to_american["clamour"] <- "clamor"
    british_to_american["endeavour"] <- "endeavor"
    
    # -ence instead of -ense
    british_to_american["defence"] <- "defense"
    british_to_american["licence"] <- "license"
    
    # -ise instead of -ize
    british_to_american["organise"] <- "organize"
    british_to_american["penalise"] <- "penalize"
    british_to_american["publicise"] <- "publicize"
    british_to_american["modernise"] <- "modernize"
    british_to_american["characterise"] <- "characterize"
    british_to_american["maximise"] <- "maximize"
    british_to_american["summarise"] <- "summarize"
    british_to_american["recognise"] <- "recognize"
    british_to_american["emphasise"] <- "emphasize"
    british_to_american["specialise"] <- "specialize"
    british_to_american["relativise"] <- "relativize"
    british_to_american["optimise"] <- "optimize"
    british_to_american["scrutinise"] <- "scrutinize"
    british_to_american["mobilise"] <- "mobilize"
    british_to_american["institutionalise"] <- "institutionalize"
    british_to_american["harmonise"] <- "harmonize"
    british_to_american["feminise"] <- "feminize"
    british_to_american["minimise"] <- "minimize"
    british_to_american["synthezise"] <- "synthesize"
    british_to_american["utilise"] <- "utilize"
    british_to_american["symbolise"] <- "symbolize"
    british_to_american["criticise"] <- "criticize"
    british_to_american["hypothesise"] <- "hypothesize"
    british_to_american["privatise"] <- "privatize"
    british_to_american["overemphasise"] <- "overemphasize"
    british_to_american["theorise"] <- "theorize"
    british_to_american["marginalise"] <- "marginalize"
    british_to_american["materialise"] <- "materialize"
    british_to_american["realise"] <- "realize"
    british_to_american["contextualise"] <- "contextualize"
    british_to_american["standardise"] <- "standardize"
    british_to_american["capitalise"] <- "capitalize"
    british_to_american["legitimise"] <- "legitimize"
    british_to_american["prioritise"] <- "prioritize"
    british_to_american["generalise"] <- "generalize"
    british_to_american["popularise"] <- "popularize"
    british_to_american["galvanise"] <- "galvanize"
    british_to_american["practise"] <- "practice"
    british_to_american["conceptualise"] <- "conceptualize"
    british_to_american["socialise"] <- "socialize"
    british_to_american["sensitise"] <- "sensitize"
    british_to_american["actualise"] <- "actualize"
    british_to_american["politicise"] <- "politicize"
    british_to_american["crystallise"] <- "crystallize"
    british_to_american["stigmatise"] <- "stigmatize"
    british_to_american["stabilise"] <- "stabilize"
    british_to_american["thematise"] <- "thematize"
    british_to_american["normalise"] <- "normalize"
    british_to_american["professionalise"] <- "professionalize"
    british_to_american["internalise"] <- "internalize"
    british_to_american["rationalise"] <- "rationalize"
    british_to_american["jeopardise"] <- "jeopardize"
    british_to_american["formalise"] <- "formalize"
    british_to_american["romanticise"] <- "romanticize"
    british_to_american["essentialise"] <- "essentialize"
    british_to_american["compartmentalise"] <- "compartmentalize"
    british_to_american["incentivise"] <- "incentivize"
    british_to_american["categorise"] <- "categorize"
    british_to_american["finalise"] <- "finalize"
    british_to_american["revitalise"] <- "revitalize"
    british_to_american["familiarise"] <- "familiarize"
    british_to_american["metabolise"] <- "metabolize"
    
    # -sation instead of -zation
    british_to_american["organisation"] <- "organization"
    british_to_american["authorisation"] <- "authorization"
    british_to_american["specialisation"] <- "specialization"
    british_to_american["legalisation"] <- "legalization"
    british_to_american["modernisation"] <- "modernization"
    british_to_american["harmonisation"] <- "harmonization"
    british_to_american["utilisation"] <- "utilization"
    british_to_american["casualisation"] <- "casualization"
    british_to_american["reorganisation"] <- "reorganization"
    british_to_american["feminisation"] <- "feminization"
    british_to_american["categorisation"] <- "categorization"
    british_to_american["thevalorisation"] <- "thevalorization"
    british_to_american["realisation"] <- "realization"
    british_to_american["mobilisation"] <- "mobilization"
    british_to_american["decentralisation"] <- "decentralization"
    british_to_american["individualisation"] <- "individualization"
    british_to_american["democratisation"] <- "democratization"
    british_to_american["revitalisation"] <- "revitalization"
    british_to_american["monopolisation"] <- "monopolization"
    british_to_american["socialisation"] <- "socialization"
    british_to_american["valorisation"] <- "valorization"
    british_to_american["formalisation"] <- "formalization"
    british_to_american["characterisation"] <- "characterization"
    british_to_american["professionalisation"] <- "professionalization"
    british_to_american["marginalisation"] <- "marginalization"
    british_to_american["problematisation"] <- "problematization"
    british_to_american["racialisation"] <- "racialization"
    british_to_american["conceptualisation"] <- "conceptualization"
    british_to_american["maximisation"] <- "maximization"
    british_to_american["generalisation"] <- "generalization"
    british_to_american["globalisation"] <- "globalization"
    british_to_american["invisibilisation"] <- "invisibilization"
    british_to_american["neutralisation"] <- "neutralization"
    british_to_american["visualisation"] <- "visualization"
    british_to_american["underutilisation"] <- "underutilization"
    british_to_american["institutionalisation"] <- "institutionalization"
    british_to_american["liberalisation"] <- "liberalization"
    british_to_american["stabilisation"] <- "stabilization"
    british_to_american["commercialisation"] <- "commercialization"
    british_to_american["stigmatisation"] <- "stigmatization"
    british_to_american["popularisation"] <- "popularization"
    british_to_american["systematisation"] <- "systematization"
    british_to_american["internationalisation"] <- "internationalization"
    british_to_american["optimisation"] <- "optimization"
    british_to_american["prioritisation"] <- "prioritization"
    british_to_american["normalisation"] <- "normalization"
    british_to_american["industrialisation"] <- "industrialization"
    british_to_american["internalisation"] <- "internalization"
    british_to_american["bureaucratisation"] <- "bureaucratization"
    british_to_american["scientisation"] <- "scientization"
    british_to_american["technicisation"] <- "technicization"
    british_to_american["contextualisation"] <- "contextualization"
    british_to_american["sensitisation"] <- "sensitization"
    british_to_american["capitalisation"] <- "capitalization"
    british_to_american["genderrelatedissueswithineuropeanorganisationsuchastheeuropeanlifescientistorganisation"] <- "genderrelatedissueswithineuropeanorganisationsuchastheeuropeanlifescientistorganization"
    british_to_american["rupisassociateprofessorattheinstituteforsocietyandglobalisation"] <- "rupisassociateprofessorattheinstituteforsocietyandglobalization"
    british_to_american["andorganisation"] <- "andorganization"
    british_to_american["especiallyintheareasofcivilsocietytransnationalmobilisation"] <- "especiallyintheareasofcivilsocietytransnationalmobilization"
    british_to_american["insitutionalisation"] <- "insitutionalization"
    british_to_american["sensibilisation"] <- "sensibilization"
    british_to_american["marketisation"] <- "marketization"
    british_to_american["politicisation"] <- "politicization"
    british_to_american["ghettoisation"] <- "ghettoization"
    british_to_american["disciplinisation"] <- "disciplinization"
    british_to_american["civilisation"] <- "civilization"
    british_to_american["customisation"] <- "customization"
    british_to_american["standardisation"] <- "standardization"
    british_to_american["naturalisation"] <- "naturalization"
    british_to_american["privatisation"] <- "privatization"
    british_to_american["centralisation"] <- "centralization"
    british_to_american["traditionalisation"] <- "traditionalization"
    british_to_american["dualisation"] <- "dualization"
    british_to_american["masculinisation"] <- "masculinization"
    british_to_american["fullnameoforganisation"] <- "fullnameoforganization"
    british_to_american["victimisation"] <- "victimization"
    british_to_american["genderisation"] <- "genderization"
    british_to_american["theresearchorganisation"] <- "theresearchorganization"
    british_to_american["legitimisation"] <- "legitimization"
    british_to_american["fertilisation"] <- "fertilization"
    british_to_american["urbanisation"] <- "urbanization"
    british_to_american["operalisation"] <- "operalization"
    british_to_american["hypersexualisation"] <- "hypersexualization"
    british_to_american["immunisation"] <- "immunization"
    british_to_american["polarisation"] <- "polarization"
    british_to_american["undercapitalisation"] <- "undercapitalization"
    british_to_american["synchronisation"] <- "synchronization"
    
    
    # -re instead of -er
    british_to_american["centre"] <- "center"
    british_to_american["meagre"] <- "meager"
    british_to_american["theatre"] <- "theater"
    british_to_american["spectre"] <- "specter"
    british_to_american["octobre"] <- "october"
    british_to_american["telecentre"] <- "telecenter"
    british_to_american["fibre"] <- "fiber"
    
    
    # -yse instead of -yze
    british_to_american["analyse"] <- "analyze"
    british_to_american["catalyse"] <- "catalyze"
    
    
    # -ogue instead of -og
    british_to_american["dialog"] <- "dialogue"
    british_to_american["catalogue"] <- "catalog"
    british_to_american["analogue"] <- "analog"
    
    
    # -eing instead of -ing
    british_to_american["ageing"] <- "aging"
    british_to_american["becomeing"] <- "becoming"
    
    # -eable instead -able
    british_to_american["sizeable"] <- "sizable"
    british_to_american["likeable"] <- "likable"
    british_to_american["knowledgeable"] <- "knowledgable"
    british_to_american["moveable"] <- "movable"
    british_to_american["recycleable"] <- "recyclable"
    british_to_american["useable"] <- "usable"
    british_to_american["measureable"] <- "measurable"
    
    return(british_to_american)
}